# Generated by Django 2.2.10 on 2020-03-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendurls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlinput',
            options={},
        ),
        migrations.RemoveField(
            model_name='urlinput',
            name='url_id',
        ),
    ]
