# Generated by Django 2.2.10 on 2020-03-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendurls', '0002_auto_20200311_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinput',
            name='url_input',
            field=models.CharField(max_length=100),
        ),
    ]
